### ISSUE TITLE
Missing presidential_candidates model?

### ISSUE THREAD

**Issue by risafangs** [DataRecce/TodoFEC-dbt#20]
I was running the dbt models from this repo locally and encounter an error with `int_contributions_to_presidential_candidates`. The opening CTE refers to a model [presidential_candidates](https://github.com/DataRecce/TodoFEC-dbt/blob/main/dbt/models/intermediate/int_contributions_to_presidential_candidates.sql) that does not appear to exist in the repo.

Output of `dbt run`:
<img width="958" alt="image" src="https://github.com/user-attachments/assets/1d6b271c-9c5b-413b-9886-8a7c8808358f">

**Comment by even-wei** [comment]
Did you run `dbt seed` before `dbt run`?

**Comment by risafangs** [comment]
That would help! Sorry, didn’t occur to me that this would be a seed when the data seems to appear in the staging files.
